
#  ____  _
# |  _ \(_)_ __  _ __       .________.
# | |_) | | '_ \| '__|      |________|
# |  __/| | |_) | |          |_    -|
# |_|   |_| .__/|_|     xX  xXx___x_|
#         |_|
#
# A commandline utility by
# Leon Kowarschick

# finish_hook: Executed once you close pipr, getting the command you constructed piped into stdin.
finish_hook = "xclip -selection clipboard -in"

# Paranoid history mode writes every sucessfully running command into the history in autoeval mode.
paranoid_history_mode_default = false
autoeval_mode_default = true
history_size = 500
cmdlist_always_show_preview = false
cmd_timeout_millis = 2000
highlighting_enabled = false
eval_environment = ["bash", "-c"]

[snippets]
s = " | sed -r 's/||//g'"

[help_viewers]
'm' = "man ??"
'h' = "?? --help | less"

[output_viewers]
'l' = "less"
